vorteil/vorteil

pkg/vimg/root.go

add inodes if using shell

---

pkg/vconvert/vconvert.go

added mac users for converter. Fixes #26. Added containerd log supression for converter Fixes #27

converter fixes

---

cmd/vorteil/run.go
go.mod
go.sum
pkg/virtualizers/firecracker/virtualizer_linux.go
pkg/virtualizers/qemu/virtualizer_notwindows.go
pkg/virtualizers/qemu/virtualizer_windows.go
pkg/virtualizers/virtualbox/virtualizer.go

Resolves #42 #41 #40, also resolves a bug with virtualbox on windows

---

cmd/vorteil/run.go
pkg/elog/logger.go
pkg/provisioners/azure/provisioner.go
pkg/vconvert/vconvert.go
pkg/vdisk/formats.go
pkg/virtualizers/firecracker/virtualizer_linux.go
pkg/virtualizers/firecracker/virtualizer_notlinux.go
pkg/virtualizers/manager.go
pkg/virtualizers/virtualizer.go
pkg/vproj/projects.go

Added more comments and exported header definitions

Goreport improvements

---

README.md
cmd/vorteil/cli.go
cmd/vorteil/projects.go
cmd/vorteil/provision.go

added help for provisioner

---

cmd/vorteil/main.go

Added spinner for download from URL. In record mode the print of every file is in debug mode only.

Debug printf

---

pkg/vio/tree.go

Adjustements to the vio/tree.go

Fixed building an image on windows

---

cmd/vorteil/run.go
cmd/vorteil/virtualizers.go
pkg/virtualizers/hyperv/virtualizer.go
pkg/virtualizers/virtualbox/virtualizer.go

Fixed issues with VirtualBox handling some errors were appearing that weren't actually an error for the action that was being taken. Suppressed them. Also moved initLogging to when were starting the virtual machine so we don't receive errors during this process that aren't related to the virtual machine.
Run VirtualBox around 30 times to see if any inconsistencies and suppressed errors that didn't affect the process.

Fixed some issues that appeared when ctrl-cing

---

pkg/imagetools/decompile.go
pkg/vconvert/guid_unix.go

Mac exporter

---

pkg/virtualizers/hyperv/virtualizer.go
pkg/virtualizers/qemu/virtualizer.go
pkg/virtualizers/qemu/virtualizer_notwindows.go
pkg/virtualizers/qemu/virtualizer_windows.go
pkg/virtualizers/virtualbox/virtualizer.go

Added loading symbols for some virtualizers as the preparing process isn't as instant as QEMU.

Hyper improvements

---

pkg/vconvert/vconvert.go

Order of channel opening was wrong so the download process could starve

fixed channel issue in converter

---

pkg/vkern/manager-compound.go

CLI would not download new kernel versions.

fixed kernel download

---

cmd/vorteil/provision.go
cmd/vorteil/virtualizers.go
pkg/vcfg/defaults.go
pkg/vdisk/build.go

Adds some default values to vcfgs at build-time if empty.
Ran tests with provisioners and virtualizers
**Operating system:** Mac

Vcfg defaults

---

pkg/imagetools/cat.go
pkg/imagetools/cp.go
pkg/imagetools/decompile.go
pkg/imagetools/du.go
pkg/imagetools/fs.go
pkg/imagetools/fsimg.go
pkg/imagetools/gpt.go
pkg/imagetools/md5sum.go
pkg/imagetools/stat.go
pkg/imagetools/tree.go
pkg/provisioners/amazon/provisioner.go

Please describe the aim of the pull request and the changes made in the commits.
Please describe how the proposed changes have been tested, and the outcome of the tests.
**Operating system:** OSX/Windows 10/Ubuntu 20.04/etc.
**CLI version:**
**Hypervisors/Platforms (if applicable):** qemu/hyper-v/google cloud platform/vmware workstation/etc
**Kernel version (if applicable):**

General cleanup

---

pkg/ext/common.go
pkg/ext/compiler.go

Adds a file-type field to directory entries.

---

pkg/vcfg/defaults.go

- Adds generating default fields for memory in DefaultVCFG

Change DefaultVCFG for generating Memory

---

cmd/vorteil/main.go
pkg/cli/cli.go
pkg/cli/provision.go
pkg/provisioners/amazon/amazon.go
pkg/provisioners/azure/azure.go
pkg/provisioners/google/google.go
pkg/provisioners/provisioners.go
pkg/provisioners/registry/registry.go
pkg/provisioners/registry/registry_test.go

New Provisioner Architecture to better support adding additional provisioners in the future.
Provisioned to AWS, GPC, and Azure to confirm provisioning logic is still working.
**Operating system:** Ubuntu 20.04

Provisioner Registry Package / Logic Implemented

---

pkg/cli/cli.go
pkg/cli/run.go
pkg/cli/virtualizers.go
pkg/virtualizers/util.go
pkg/virtualizers/vmware/allocator.go
pkg/virtualizers/vmware/virtualizer.go
pkg/virtualizers/vmware/virtualizer_notwindows.go
pkg/virtualizers/vmware/virtualizer_test.go
pkg/virtualizers/vmware/virtualizer_windows.go

Making vmware work with the virtualizer drivers.

Vmware implementation

---

pkg/vcfg/bootstrap.go
pkg/vimg/os.go

Set rw as default for first disk

rw disk default

---

pkg/provisioners/google/google.go

Remove a TODO
